### ISSUE TITLE
Your Setup 

### ISSUE THREAD

**Issue by dknaack** [effyteva/CSharpLibraries#1]
Hey!

Iam considering using and contributing to your library.
Iam wondering what setup are you using meaning which Server etc.?

Regards Denis

**Comment by effyteva** [comment]
Hi Denis,

For my testing setup, I'm using local cluster of 3 Cassandra instances, with a single local Titan 1.0 server.
Does this answer your question?

I've re-synced the code with my latest updates, please make sure to use the latest one.

Your contributing will be appreciated!

Regards,
Effy

**Comment by dknaack** [comment]
Yes, thats answers my question. Thank you for the fast response! I have a look at the code.

**Comment by dknaack** [comment]
A few more questions about your setup.

- Do you connect to a rexster server or how you do it? 
- Do you host your this on your Windows machine?

I am using Titan + Cassandra + Elasticsearch at the momen. 

Thanks in advance

**Comment by effyteva** [comment]
I'm connecting to Titan Server (Gremlin Server).
Rexster has been renamed to Gremlin Server in TinkerPop 3.

Yes, I host this on a Windows machine.
I'm currently using Titan + Cassandra without ES.

Effy
