### ISSUE TITLE
Small bug in Append_DeleteVertexByIndexAndLabel

### ISSUE THREAD

**Issue by SecSan** [effyteva/CSharpLibraries#4]
Hi,

I just found a small bug that was probably introduced while merging in my pull-request. The function `GremlinScript.Append_DeleteVertexByIndexAndLabel` doesn't use the `Label` parameter. It simply calls `Append_GetVerticesByIndex`, instead it should call `Append_GetVerticesByIndexAndLabel`.

Would be nice if you could fix that.

Regards,
SecSan

**Comment by effyteva** [comment]
Thanks SecSan,
I'll do my best to fix and share my fix today.

**Comment by effyteva** [comment]
Sorry for the Delay SecSan,

I've finally managed to merge this change, and publish it on NuGet.

Regards,
Effy

On Mon, Mar 7, 2016 at 11:02 AM, SecSan <notifications@github.com> wrote:

> Hi,
>
> I just found a small bug that was probably introduced while merging in my
> pull-request. The function
> GremlinScript.Append_DeleteVertexByIndexAndLabel doesn't use the Label
> parameter. It simply calls Append_GetVerticesByIndex, instead it should
> call Append_GetVerticesByIndexAndLabel.
>
> Would be nice if you could fix that.
>
> Regards,
> SecSan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/effyteva/CSharpLibraries/issues/4>.
>

ᐧ

**Comment by SecSan** [comment]
Thanks!
